/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;
import Controleur.Controleur;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;


/**
 *
 * @author silu
 */
public class AcueilResponsable extends javax.swing.JFrame {
    private String text ="";
   

    /**
     * Creates new form AcueilResponsable
     */
    public AcueilResponsable() {
        initComponents();
        
    }
    public AcueilResponsable(String name) {
        initComponents();
        this.setAlwaysOnTop(true);
        this.text = name;
        this.lblName.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deconnexion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gestionSalle = new javax.swing.JButton();
        planningSalle = new javax.swing.JButton();
        gestionCompteEtu = new javax.swing.JButton();
        gestionMachine = new javax.swing.JButton();
        gestionReclamation = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deconnexion.setText("Déconnexion");
        deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenue");

        gestionSalle.setText("Gestion des salles");
        gestionSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionSalleActionPerformed(evt);
            }
        });

        planningSalle.setText("Gestion les plnnings des salles");
        planningSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planningSalleActionPerformed(evt);
            }
        });

        gestionCompteEtu.setText("Gestion des comptes etudiants");
        gestionCompteEtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionCompteEtuActionPerformed(evt);
            }
        });

        gestionMachine.setText("Gestion des machines");
        gestionMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionMachineActionPerformed(evt);
            }
        });

        gestionReclamation.setText("Gestion des Réclamation");
        gestionReclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionReclamationActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addGap(223, 223, 223)
                .addComponent(deconnexion)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gestionReclamation, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(gestionMachine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(planningSalle, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(gestionCompteEtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gestionSalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deconnexion)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gestionSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(planningSalle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionCompteEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gestionReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionMachineActionPerformed
        // TODO add your handling code here:
        ListMachine lm=new ListMachine(text);
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionMachineActionPerformed

    private void gestionSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionSalleActionPerformed
        // TODO add your handling code here:
        
        ListSalles l=new ListSalles(text);
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionSalleActionPerformed

    private void gestionCompteEtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionCompteEtuActionPerformed
        // TODO add your handling code here:
       // System.out.println(this.lblName.getText());
        
        ListCompteEtudiant LCE = new ListCompteEtudiant(this.lblName.getText());  
        
        LCE.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_gestionCompteEtuActionPerformed

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        new Connexion().setVisible(true);
        dispose();
    }//GEN-LAST:event_deconnexionActionPerformed

    private void gestionReclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionReclamationActionPerformed
        // TODO add your handling code here:
        ListeReclamations listRec = new ListeReclamations(text);
        listRec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gestionReclamationActionPerformed

    private void planningSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planningSalleActionPerformed
        // TODO add your handling code here:
        AjouterPlanning aPlanning = new AjouterPlanning(text);
        aPlanning.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_planningSalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcueilResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcueilResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcueilResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcueilResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AcueilResponsable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexion;
    private javax.swing.JButton gestionCompteEtu;
    private javax.swing.JButton gestionMachine;
    private javax.swing.JButton gestionReclamation;
    private javax.swing.JButton gestionSalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton planningSalle;
    // End of variables declaration//GEN-END:variables
}
