/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.Controleur;
import Models.Salle;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author silu
 */
public class AjouterMachine extends javax.swing.JFrame {
    private Controleur c=new Controleur();
    /**
     * Creates new form AjouterMachine
     */
    public AjouterMachine() {
        initComponents();
    }
    
    public AjouterMachine(String name){
        initComponents();
        this.lblnomprenomR1.setText(name);
        ArrayList<Salle> tlS=c.tousLesSalle();
        String[] nomSalle= new String[tlS.size()];
        for(int i=0;i<tlS.size();i++){
            nomSalle[i]=tlS.get(i).getNumeroSalle();
        }
        this.cmbIdSalle.setModel(new DefaultComboBoxModel<>(nomSalle));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmerAjouterMachine = new javax.swing.JButton();
        retourListMachine = new javax.swing.JButton();
        txtIdMachineA = new javax.swing.JTextField();
        lblnomprenomR1 = new javax.swing.JLabel();
        cmbEtatM = new javax.swing.JComboBox<>();
        cmbIdSalle = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenue");

        jLabel2.setText("Id Machine:");

        jLabel3.setText("Etat Machine:");

        jLabel4.setText("Id Salle:");

        confirmerAjouterMachine.setText("Ajouter");
        confirmerAjouterMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerAjouterMachineActionPerformed(evt);
            }
        });

        retourListMachine.setText("Retour Liste des Machine");
        retourListMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourListMachineActionPerformed(evt);
            }
        });

        lblnomprenomR1.setText("...");

        cmbEtatM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fonctionne", "panne" }));
        cmbEtatM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEtatMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmerAjouterMachine)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(retourListMachine)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(83, 83, 83)
                                .addComponent(lblnomprenomR1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbEtatM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdMachineA, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbIdSalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblnomprenomR1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMachineA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbEtatM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbIdSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmerAjouterMachine)
                    .addComponent(retourListMachine))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourListMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourListMachineActionPerformed
        // TODO add your handling code here:
        ListMachine lm =new ListMachine(this.lblnomprenomR1.getText());
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retourListMachineActionPerformed

    private void confirmerAjouterMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerAjouterMachineActionPerformed
        // TODO add your handling code here:
        String idm=this.txtIdMachineA.getText();
        String etatm=(String)this.cmbEtatM.getSelectedItem();
        
        String ids=(String)this.cmbIdSalle.getSelectedItem();
        
        Controleur c=new Controleur();
        if(c.verifierNbMachine(ids)){
            c.ajouterMachine(idm, etatm, ids);
        
            ListMachine lm=new ListMachine(this.lblnomprenomR1.getText());
            lm.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Le nombre de machine est superieur la capacité de la salle.");
        }
        
    }//GEN-LAST:event_confirmerAjouterMachineActionPerformed

    private void cmbEtatMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEtatMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEtatMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEtatM;
    private javax.swing.JComboBox<String> cmbIdSalle;
    private javax.swing.JButton confirmerAjouterMachine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblnomprenomR1;
    private javax.swing.JButton retourListMachine;
    private javax.swing.JTextField txtIdMachineA;
    // End of variables declaration//GEN-END:variables
}
