package Vue;

import ConnectionBD.ConnectionBD;
import Controleur.Controleur;
import Models.Machine;
import Models.Reclamation;
import Models.User;
import java.sql.Connection;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 21911890
 */
public class FaireReclamation extends javax.swing.JFrame {
    private User etudiant ;
    private Machine machine ;
    
  
    /**
     * Creates new form Reclamation
     */
    public FaireReclamation() {
        initComponents();
    }
    
    public FaireReclamation(User etudiant, Machine machine){
        initComponents();
        this.etudiant= etudiant;
        this.machine = machine; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFieldDescRec = new javax.swing.JTextArea();
        validerRec = new javax.swing.JButton();
        annulerRec = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtFieldobjRec = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DEPOSER UNE RECLAMATION");

        jLabel10.setText("Description :");

        txtFieldDescRec.setColumns(20);
        txtFieldDescRec.setRows(5);
        jScrollPane1.setViewportView(txtFieldDescRec);

        validerRec.setText("Valider");
        validerRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerRecActionPerformed(evt);
            }
        });

        annulerRec.setText("Retour");
        annulerRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerRecActionPerformed(evt);
            }
        });

        jLabel6.setText("Objet");

        txtFieldobjRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldobjRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFieldobjRec, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(annulerRec, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(validerRec, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldobjRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validerRec)
                    .addComponent(annulerRec))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerRecActionPerformed
        // TODO add your handling code here:
       ConsulterEtGererReservations consRes = new ConsulterEtGererReservations(etudiant);
       consRes.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_annulerRecActionPerformed

    private void txtFieldobjRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldobjRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldobjRecActionPerformed

    private void validerRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerRecActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        String objRec= txtFieldobjRec.getText();
        String contenuRec = txtFieldDescRec.getText();
        java.util.Date date=new java.util.Date();
	java.sql.Date dateRec=new java.sql.Date(date.getTime());
        // pour le teste 
        this.etudiant = new User("21809085");
        this.machine = new Machine("A12870");
        try {
            conn = ConnectionBD.getConnection();
             Reclamation reclamation = new Reclamation(this.etudiant,this.machine,objRec,contenuRec,dateRec);
            if (Controleur.addReclamation(conn, reclamation)!=0){
                Controleur.sendEmail("ucapitole@gmail.com");
                 JOptionPane.showMessageDialog(null, "réclamation insérée");
                 txtFieldDescRec.setText("");
                 txtFieldobjRec.setText("");
            }else{
              JOptionPane.showMessageDialog(null, "insertion erreur !!");  
            }    
            
        }catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "connexion echec");
        }finally {
            try {
                ConnectionBD.closeConn(conn);
            }catch(Exception e){
                e.printStackTrace();
            }
        } 
    }//GEN-LAST:event_validerRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaireReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaireReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaireReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaireReclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaireReclamation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtFieldDescRec;
    private javax.swing.JTextField txtFieldobjRec;
    private javax.swing.JButton validerRec;
    // End of variables declaration//GEN-END:variables
}
