/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.Controleur;
import Models.Salle;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author silu
 */
public class ListSalles extends javax.swing.JFrame {
    private Controleur c=new Controleur();

    /**
     * Creates new form ListSalles
     */
    public ListSalles() {
        initComponents();
        
        ArrayList<Salle> touslesSalles=new ArrayList<Salle>();
      
        touslesSalles = c.tousLesSalle();
        
        DefaultTableModel model =(DefaultTableModel)tableSalles.getModel();
        Object rowData[]=new Object[touslesSalles.size()];
        for(int i =0;i<touslesSalles.size();i++){
            rowData[0] = touslesSalles.get(i).getNumeroSalle();
            rowData[1] = touslesSalles.get(i).getNbMachineMax();
            rowData[2] = touslesSalles.get(i).getEtatSalle();
            model.addRow(rowData);
        }
    }
    
    public ListSalles(String name){
        initComponents();
        this.lblName.setText(name);
        ArrayList<Salle> touslesSalles=new ArrayList<Salle>();
        
        touslesSalles = c.tousLesSalle();
        
        DefaultTableModel model =(DefaultTableModel)tableSalles.getModel();
        Object rowData[]=new Object[touslesSalles.size()];
        for(int i =0;i<touslesSalles.size();i++){
            rowData[0] = touslesSalles.get(i).getNumeroSalle();
            rowData[1] = touslesSalles.get(i).getNbMachineMax();
            rowData[2] = touslesSalles.get(i).getEtatSalle();
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retourAccResp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalles = new javax.swing.JTable();
        ajouterSalle = new javax.swing.JButton();
        modifierSalle = new javax.swing.JButton();
        supprimerSalle = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        retourAccResp.setText("Retour Accueil");
        retourAccResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourAccRespActionPerformed(evt);
            }
        });

        jLabel1.setText("Bienvenue");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Liste des salles");

        tableSalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Salle", "Nombre Machine Max", "Etat Salle"
            }
        ));
        jScrollPane1.setViewportView(tableSalles);

        ajouterSalle.setText("Ajouter Salle");
        ajouterSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterSalleActionPerformed(evt);
            }
        });

        modifierSalle.setText("Modifier Salle");
        modifierSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierSalleActionPerformed(evt);
            }
        });

        supprimerSalle.setText("Supprimer Salle");
        supprimerSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerSalleActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(modifierSalle)
                .addGap(18, 18, 18)
                .addComponent(supprimerSalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ajouterSalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retourAccResp)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(lblName)
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterSalle)
                    .addComponent(retourAccResp)
                    .addComponent(modifierSalle)
                    .addComponent(supprimerSalle))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourAccRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourAccRespActionPerformed
        // TODO add your handling code here:
        
        AcueilResponsable a=new AcueilResponsable(this.lblName.getText());
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retourAccRespActionPerformed

    private void modifierSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierSalleActionPerformed
        // TODO add your handling code here:
        int row = tableSalles.getSelectedRow();
        String ids=(String)tableSalles.getValueAt(row, 0);
        
        Salle s=c.afficherUneSalle(ids);
        ModifierSalle m=new ModifierSalle(this.lblName.getText(),s);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modifierSalleActionPerformed

    private void ajouterSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterSalleActionPerformed
        // TODO add your handling code here:
        AjouterSalle as=new AjouterSalle(this.lblName.getText());
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ajouterSalleActionPerformed

    private void supprimerSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerSalleActionPerformed
        // TODO add your handling code here:
        int row = tableSalles.getSelectedRow();
        String ids=(String)tableSalles.getValueAt(row, 0);
        
        int count=c.supprimerSalle(ids);
        if(count==1){
            ListSalles ls=new ListSalles(this.lblName.getText());
            ls.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "echec de supprimer");
        }
        
        
    }//GEN-LAST:event_supprimerSalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListSalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListSalles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterSalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JButton modifierSalle;
    private javax.swing.JButton retourAccResp;
    private javax.swing.JButton supprimerSalle;
    private javax.swing.JTable tableSalles;
    // End of variables declaration//GEN-END:variables
}
