/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.Controleur;
import Models.Salle;
import javax.swing.JOptionPane;

/**
 *
 * @author silu
 */
public class ModifierSalle extends javax.swing.JFrame {

    /**
     * Creates new form ModifierSalle
     */
    public ModifierSalle() {
        initComponents();
    }
    
    public ModifierSalle(String name,Salle s){
        initComponents();
        this.lblnomprenomR.setText(name);
        this.lblIdS.setText(s.getNumeroSalle());
        this.txtNbMachaineM.setText(String.valueOf(s.getNbMachineMax()));
        this.cmbEtatS.setSelectedItem(s.getEtatSalle());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deconnexion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblnomprenomR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNbMachaineM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmerModifierSalle = new javax.swing.JButton();
        retourListeSalles = new javax.swing.JButton();
        lblIdS = new javax.swing.JLabel();
        cmbEtatS = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deconnexion.setText("Déconnexion");
        deconnexion.setToolTipText("");

        jLabel1.setText("Bienvenue");

        lblnomprenomR.setText("...");

        jLabel2.setText("id Salle:");

        jLabel3.setText("Nombre Machaine Max:");

        jLabel4.setText("Etat:");

        confirmerModifierSalle.setText("Modifier");
        confirmerModifierSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerModifierSalleActionPerformed(evt);
            }
        });

        retourListeSalles.setText("Retour Liste des Salles");
        retourListeSalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourListeSallesActionPerformed(evt);
            }
        });

        lblIdS.setText("idS");

        cmbEtatS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ouvert", "ferme" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNbMachaineM, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdS)
                    .addComponent(cmbEtatS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(confirmerModifierSalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(retourListeSalles))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(lblnomprenomR)))
                .addGap(43, 43, 43)
                .addComponent(deconnexion)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deconnexion)
                    .addComponent(jLabel1)
                    .addComponent(lblnomprenomR))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdS))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNbMachaineM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cmbEtatS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmerModifierSalle)
                    .addComponent(retourListeSalles))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourListeSallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourListeSallesActionPerformed
        // TODO add your handling code here:
        ListSalles l=new ListSalles(this.lblnomprenomR.getText());
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retourListeSallesActionPerformed

    private void confirmerModifierSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerModifierSalleActionPerformed
        // TODO add your handling code here:
        String ids=this.lblIdS.getText();
        Integer nbm=Integer.valueOf(this.txtNbMachaineM.getText());
        String etats=(String)this.cmbEtatS.getSelectedItem();
        Controleur c=new Controleur();
        int count =c.modifierSalle(ids,nbm,etats);
        if(count==1){
            ListSalles l=new ListSalles(this.lblnomprenomR.getText());
            l.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "echec de modifier");
        }
    }//GEN-LAST:event_confirmerModifierSalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierSalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierSalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEtatS;
    private javax.swing.JButton confirmerModifierSalle;
    private javax.swing.JButton deconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIdS;
    private javax.swing.JLabel lblnomprenomR;
    private javax.swing.JButton retourListeSalles;
    private javax.swing.JTextField txtNbMachaineM;
    // End of variables declaration//GEN-END:variables
}
