/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Controleur.Controleur;
import Models.Machine;
import Models.Salle;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author silu
 */
public class ModifierMachine extends javax.swing.JFrame {
    private Controleur c=new Controleur();
    
    /**
     * Creates new form ModifierMachine
     */
    public ModifierMachine() {
        initComponents();
    }
    
    public ModifierMachine(String name,Machine m){
        initComponents();
        this.lblName.setText(name);
        this.lblIdM.setText(m.getIdM());
        this.cmbEtatM.setSelectedItem(m.getEtatM());
        
        ArrayList<Salle> tlS=c.tousLesSalle();
        String[] nomSalle= new String[tlS.size()];
        for(int i=0;i<tlS.size();i++){
            nomSalle[i]=tlS.get(i).getNumeroSalle();
        }
        this.cmbIdS.setModel(new DefaultComboBoxModel<>(nomSalle));
        this.cmbIdS.setSelectedItem(m.getIdS());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnomprenomR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmerModifierMachine = new javax.swing.JButton();
        retourListMachine = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblIdM = new javax.swing.JLabel();
        cmbIdS = new javax.swing.JComboBox<>();
        cmbEtatM = new javax.swing.JComboBox<>();

        lblnomprenomR.setText("...");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenue");

        deconnexion.setText("Déconnexion");

        jLabel2.setText("Id Machine:");

        jLabel3.setText("Etat Machine:");

        jLabel4.setText("Id Salle:");

        confirmerModifierMachine.setText("Modifier");
        confirmerModifierMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmerModifierMachineActionPerformed(evt);
            }
        });

        retourListMachine.setText("Retour Liste des Machine");
        retourListMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourListMachineActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblIdM.setText("idM");

        cmbEtatM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "fonctionne", "panne" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addGap(34, 34, 34)
                .addComponent(deconnexion)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirmerModifierMachine)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(retourListMachine))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdM)
                            .addComponent(cmbEtatM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbIdS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deconnexion)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdM))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbEtatM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmerModifierMachine)
                            .addComponent(retourListMachine)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cmbIdS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourListMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourListMachineActionPerformed
        // TODO add your handling code here:
        ListMachine lm =new ListMachine(this.lblName.getText());
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retourListMachineActionPerformed

    private void confirmerModifierMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmerModifierMachineActionPerformed
        // TODO add your handling code here:
        String idm=this.lblIdM.getText();
        String etatm=(String)this.cmbEtatM.getSelectedItem();
        String ids=(String)this.cmbIdS.getSelectedItem();
        Controleur c=new Controleur();
        int count =c.modifierMachine(idm,etatm,ids);
        if(count==1){
            ListMachine lm =new ListMachine(this.lblName.getText());
            lm.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "echec de modifier");
        }
    }//GEN-LAST:event_confirmerModifierMachineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbEtatM;
    private javax.swing.JComboBox<String> cmbIdS;
    private javax.swing.JButton confirmerModifierMachine;
    private javax.swing.JButton deconnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblIdM;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblnomprenomR;
    private javax.swing.JButton retourListMachine;
    // End of variables declaration//GEN-END:variables
}
